### ISSUE TITLE
Picture + Questions

### ISSUE THREAD

**Issue by vekexasia** [Adminius/ESP32-ScanMyTesla#1]
Hey there, can you post a picture of this setup? 

Expecially about the SN65HVD230. I'm curious why and how to recognize if a module has or not the resistor. (And why we dont want that?)

Also where did you take the relevant ids from?

**Comment by Adminius** [comment]
Hi, 
I'm using this break out board and it has termination resistor, that has to be removed
![Screenshot_20210106-134249_Chrome](https://user-images.githubusercontent.com/17052262/103769766-30f05180-5025-11eb-9a6d-cca42cd1bfbd.jpg)
There are only 2 terminaion resistors allowed on can bus. On both can bus wiring ends...bur ESP32 is in the middle ;)

You don't need any IDs, SMT sets all needed by it self. My array is "extract" from SMT for test purposes.

But here you find all known IDs:
https://github.com/joshwardell/model3dbc/blob/master/Model3CAN.dbc

**Comment by vekexasia** [comment]
I was looking to buy that as well. But I was more curious about why we need to remove that resistor.

PS: Thanks for the infos.

**Comment by vekexasia** [comment]
Also, that model seems to not be working in "write" direction. (Which is a good thing in case of our Teslas) did you manage to have a go with that on some other project by writing stuff in the canbus?

**Comment by Adminius** [comment]
It can write to CAN, I use it with my Tesla to wake it up via CAN in my other project.
Write or nor can be simply managed be changing second resistor. But by default write is possible.

**Comment by vekexasia** [comment]
I am trying to buy those but all the comments in amazon.it says that it does not work in write direction. did you buy those in amazon or somewhere else?

Do you have a direct contact icould use to contact you to ask some questions? Ex: Telegram?

**Comment by Adminius** [comment]
Hi, sorry, missed you question.
My SN65HVD230 is from Aliexpress, but this boards are all equal or similar...
At least one of my board can write to the can bus, all other I tested in for reading only
According to datasheet, for read-only-mode=stand-by there have to be a strong pull up resistor.
![image](https://user-images.githubusercontent.com/17052262/169290409-b7e62ca8-8874-4242-b79d-18c0b02cb047.png)
https://www.ti.com/lit/ds/symlink/sn65hvd230.pdf
So, all users that are complain about "read only" have to checkt if it is case ;)

Here you can clearly see, that resistor is connected to ground => not a standby mode => it can write
![image](https://user-images.githubusercontent.com/17052262/169291448-21e4fd60-48e7-4663-8719-f44dae39e995.png)
103 => 10k => slope control mode
